name: r11_localizador
description: "localizador de trenes en la linea R11"
publish_to: 'none'
version: 0.1.3+2

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ^8.0.0
  ota_update: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/estaciones.json
    
# Configuramos la ruta de tu imagen personalizada para Android
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/r11_icon.png"
  min_sdk_android: 21 # Garantiza compatibilidad con vectores modernos
